image: eclipse-temurin:21

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script:
    - ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  services:
    - postgres:17.2-alpine
  variables:
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_hospitalManagement_db:5432/hospitalManagement
    SPRING_DATASOURCE_USERNAME: spring
    SPRING_DATASOURCE_PASSWORD: spring
    SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    SPRING_SQL_INIT_MODE: never
    SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    SPRING_PROFILES_ACTIVE: test
  script:
    - ./gradlew check --no-daemon
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
