spring.application.name=programming5Project
spring.datasource.url=jdbc:postgresql://localhost:5050/hospitalManagement
spring.datasource.username=spring
spring.datasource.password=spring
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create
spring.profiles.active=jpa
spring.jpa.show-sql=true

logging.level.root=info
logging.level.org.example.programming5project=debug
spring.mvc.static-path-pattern=/static/**
spring.messages.basename=messages

#for inserting entities from data.sql
spring.sql.init.data-locations=classpath:sql/data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.open-in-view=false