### to get all patients
GET http://localhost:8080/api/patients
Accept: application/json


### to delete a patient
DELETE http://localhost:8080/api/patients/P003
X-CSRF-TOKEN: Mt3nEa5QUphUJ_IO-5HPLcVkSNx3UaYkBFmxju8SUFwGvmK_AunTJpxoYat5Fpc-z7z7H_xRZb0SMsIJYjjT7IslZz43iFKN
Cookie: JSESSIONID=A2DBAE9BD9D55F8CD1D9F5145182D51B
//after running, run previous one and youll see that patient
//with this id is deleted.

### to search for a hospital
GET http://localhost:8080/api/hospitals?search=uptown
Accept: application/json


### to add patient
POST http://localhost:8080/api/patients
Content-Type: application/json
X-CSRF-TOKEN: qnbi80IFl5HVx7pCdyAXaVcPAoW1dd8WNuDcLULyOUht7NyvmELQwHEyoqj4945wEg0jCGNsL-TTTLs7AtDuG3vDDS5Viu2d
Cookie: JSESSIONID=71A7FF39C1A4AD4D7825112B20FA7CF9


{
  "firstName": "Test2",
  "lastName": "Patient",
  "age": 40,
  "gender": "MALE",
  "admissionDate": "2025-04-03",
  "billingAmount": 1234.56
}
###
# @no-redirect
# @no-cookie-jar
PATCH http://localhost:8080/api/patients/P006
Content-Type: application/json
Cookie: JSESSIONID=A2DBAE9BD9D55F8CD1D9F5145182D51B
X-CSRF-TOKEN: Mt3nEa5QUphUJ_IO-5HPLcVkSNx3UaYkBFmxju8SUFwGvmK_AunTJpxoYat5Fpc-z7z7H_xRZb0SMsIJYjjT7IslZz43iFKN

{
  "billingAmount": 5000,
  "admissionDate": "2025-03-01"
}


